@php
    $aiSummary = $record->aiSummary;
    $keyFacts = $aiSummary?->key_facts ?? [];
    $comparisons = $aiSummary?->field_comparisons ?? [];
    $statusColors = ['match' => '#166534', 'blank_fill' => '#92400E', 'mismatch' => '#B91C1C'];
    $statusLabels = ['match' => 'Match', 'blank_fill' => 'CRM blank', 'mismatch' => 'Mismatch'];
@endphp

<div style="display: flex; flex-direction: column; gap: 16px;">
    <div>
        <div style="font-size: 0.75rem; color: #4A5568; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px;">Summary</div>
        <div style="font-size: 0.9rem; line-height: 1.6;">{{ $aiSummary?->summary ?: 'No summary available.' }}</div>
    </div>

    <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 12px;">
        <div>
            <div style="font-size: 0.75rem; color: #4A5568; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px;">Document type</div>
            <div style="font-size: 0.9rem;">{{ $keyFacts['document_type'] ?: '—' }}</div>
        </div>

        <div>
            <div style="font-size: 0.75rem; color: #4A5568; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px;">Names mentioned</div>
            <div style="font-size: 0.9rem;">{{ filled($keyFacts['names'] ?? []) ? implode(', ', $keyFacts['names']) : '—' }}</div>
        </div>

        <div>
            <div style="font-size: 0.75rem; color: #4A5568; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px;">Dates mentioned</div>
            <div style="font-size: 0.9rem;">{{ filled($keyFacts['dates'] ?? []) ? implode(', ', $keyFacts['dates']) : '—' }}</div>
        </div>

        <div>
            <div style="font-size: 0.75rem; color: #4A5568; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px;">Monetary figures</div>
            <div style="font-size: 0.9rem;">{{ filled($keyFacts['monetary_figures'] ?? []) ? implode(', ', $keyFacts['monetary_figures']) : '—' }}</div>
        </div>
    </div>

    @if (filled($comparisons))
        <div>
            <div style="font-size: 0.75rem; color: #4A5568; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px;">CRM field comparison</div>
            <table style="width: 100%; border-collapse: collapse; font-size: 0.85rem;">
                <thead>
                    <tr style="text-align: left; border-bottom: 1px solid #D8DBE0;">
                        <th style="padding: 6px 4px;">Field</th>
                        <th style="padding: 6px 4px;">Document says</th>
                        <th style="padding: 6px 4px;">CRM record</th>
                        <th style="padding: 6px 4px;">Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($comparisons as $field)
                        <tr style="border-bottom: 1px solid #F4F5F7;">
                            <td style="padding: 6px 4px;">{{ $field['label'] }}</td>
                            <td style="padding: 6px 4px;">{{ $field['extracted'] }}</td>
                            <td style="padding: 6px 4px;">{{ $field['crm'] ?: '—' }}</td>
                            <td style="padding: 6px 4px; color: {{ $statusColors[$field['status']] ?? '#1C2430' }}; font-weight: 600;">
                                {{ $statusLabels[$field['status']] ?? $field['status'] }}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        @if ($aiSummary?->needs_review)
            <div style="background: #FEF3C7; border: 1px solid #FDE68A; border-radius: 6px; padding: 10px 12px; font-size: 0.85rem; color: #92400E;">
                {{ $aiSummary->review_reason }}
                @if ($aiSummary->reviewed_at)
                    <div style="margin-top: 4px; font-size: 0.75rem;">Reviewed by {{ $aiSummary->reviewedBy?->name }} on {{ $aiSummary->reviewed_at->format('d M Y, H:i') }}.</div>
                @endif
            </div>
        @endif
    @endif

    <div style="font-size: 0.7rem; color: #A9B2C0;">
        Generated by AI — verify against the original document before relying on this.
    </div>
</div>
